# Generated by Django 4.0.1 on 2022-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0003_rename_proxy host_proxy_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aclicker',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='siteweb',
            options={'verbose_name': 'URL cliquée', 'verbose_name_plural': 'URL cliquées'},
        ),
        migrations.AddConstraint(
            model_name='proxy',
            constraint=models.UniqueConstraint(fields=('host', 'password'), name='unique_host_password_couple'),
        ),
    ]
